semana02/dia5/app/forms.py
from wsgiref.validate import validator
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired

class LoginForm(FlaskForm):
  usuario = StringField('Usuario', validators=[DataRequired()])
  password = PasswordField('Password', validators=[DataRequired()])
  submit = SubmitField('Login')
  
class ProyectoForm(FlaskForm):
    codigo = StringField('Codigo',validators=[DataRequired()])
    nombre = StringField('Nombre',validators=[DataRequired()])
    descripcion = StringField('Descripcion',validators=[DataRequired()])
    imagen = StringField('Imagen',validators=[DataRequired()])
    url = StringField('Url',validators=[DataRequired()])
    submit = SubmitField('Agregar')
  

semana02/dia5/app/__init__.py
from ensurepip import bootstrap
from flask import Flask

from flask_bootstrap import Bootstrap

# importando blueprint

from .admin import admin

from .portafolio import portafolio

# importamos config

from .config import Config

def create_app():
    app = Flask(__name__)
    
    bootstrap = Bootstrap(app)
    
    app.config.from_object(Config)
    
    app.register_blueprint(admin)
    app.register_blueprint(portafolio)
    return app

semana02/dia5/app/admin/__init__.py
from flask import Blueprint

admin = Blueprint('admin', __name__, url_prefix='/admin')

from . import views

semana02/dia5/app/admin/views.py
from flask import (
    render_template,redirect,
    url_for,session,
    flash)

from . import admin

#importamos los formularios
from app.forms import LoginForm, ProyectoForm


#### para autenticación de usuarios #######
import pyrebase
from app.auth_token import firebaseConfig

firebase = pyrebase.initialize_app(firebaseConfig)
auth = firebase.auth()
###########################################

from app.firebaseAdmin import db

@admin.route('/')
def index():
    if('token' in session):
        return render_template('admin/index.html')
    else:
        return redirect(url_for('admin.login'))
        
@admin.route('/login',methods=['GET','POST'])
def login():
    login_form = LoginForm()
    context = {
        'login_form':login_form
    }
    #CODIGO PARA LOGIN DE USUARIOS
    if login_form.validate_on_submit():
        usuarioData = login_form.usuario.data
        passwordData = login_form.password.data

        try:
            usuario = auth.sign_in_with_email_and_password(usuarioData,passwordData)
            dataUsuarioValido = auth.get_account_info(usuario['idToken'])
            print(dataUsuarioValido)
            session['token'] = usuario['idToken']
            return redirect(url_for('admin.index'))
        except:
            print("usuario incorrecto")
            flash("Usuario o password invalidos")

    return render_template('admin/login.html',**context)

@admin.route('/logout')
def logout():
    session.pop('token')
    return redirect(url_for('admin.login'))

@admin.route('/proyectos',methods=['GET','POST'])
def proyectos():
    if('token' in session):
           
        #Formulario de proyectos
        colProyectos = db.collection('proyectos')
        proyecto_form = ProyectoForm()
        
        if proyecto_form.validate_on_submit():
            codigo = proyecto_form.codigo.data
            nombre = proyecto_form.nombre.data
            descripcion = proyecto_form.descripcion.data
            imagen = proyecto_form.imagen.data
            url = proyecto_form.url.data

            dataNuevoProyecto = {
                'codigo':codigo,
                'nombre':nombre,
                'descripcion':descripcion,
                'imagen':imagen,
                'url':url
            }
        
            colProyectos.document().set(dataNuevoProyecto)
        
        #Obtenemos los proyectos
        docProyectos = colProyectos.get()
        lstProyectos = []
        for doc in docProyectos:
            dicProyectos = doc.to_dict()
            lstProyectos.append(dicProyectos)
                  
        context = {
            'proyectos':lstProyectos,
            'proyecto_form':proyecto_form
        }
        return render_template('admin/proyectos.html', **context)
    else:
        return redirect(url_for('admin.login'))

semana02/dia5/app/portafolio/__init__.py
from flask import Blueprint

portafolio = Blueprint('portafolio', __name__, url_prefix='/')

from . import views

semana02/dia5/app/portafolio/views.py
from flask import Flask,render_template,request,session

from . import portafolio

from app.firebaseAdmin import db

@portafolio.route('/')
def home():
    colBiografia = db.collection('biografia')
    docBiografia = colBiografia.get()

    for doc in docBiografia:
        dicBiografia = doc.to_dict()

    session['biografia'] = dicBiografia

    #recuperamos la info de los enlaces
    colEnlaces = db.collection('enlaces')
    docEnlaces = colEnlaces.get()

    lstEnlaces = []
    for doc in docEnlaces:
        dicEnlace = doc.to_dict()
        lstEnlaces.append(dicEnlace)

    session['enlaces'] = lstEnlaces
    return render_template('portafolio/home.html')

############### RUTAS DE MIS PAGINAS
@portafolio.route('/acercade')
def about():
    return render_template('portafolio/acercade.html')

@portafolio.route('/proyectos')
def proyectos():
    colProyectos = db.collection('proyectos')
    docProyectos = colProyectos.get()

    lstProyectos = []
    for doc in docProyectos:
        print(doc.to_dict())
        dicProyecto = doc.to_dict()
        lstProyectos.append(dicProyecto)


    context = {
        'proyectos':lstProyectos
    }
    return render_template('portafolio/portafolio.html',**context)

@portafolio.route('/contacto')
def contacto():
    return render_template('portafolio/contacto.html')
   

semana02/dia5/app/templates/portafolio/acercade.html
{% extends 'portafolio/layout.html' %}
{% block content %}
        <!-- About Section-->
        <section class="page-section bg-primary text-white mb-0" id="about">
          <div class="container">
              <!-- About Section Heading-->
              <h2 class="page-section-heading text-center text-uppercase text-white">About</h2>
              <!-- Icon Divider-->
              <div class="divider-custom divider-light">
                  <div class="divider-custom-line"></div>
                  <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                  <div class="divider-custom-line"></div>
              </div>
              <!-- About Section Content-->
              <div class="row">
                <div class="col-lg-6 ms-auto">
                    <img class="masthead-avatar mb-5" src="{{session.biografia['foto']}}" alt="..." />
                </div>
                
                  <div class="col-lg-6 ms-auto "><p class="lead">{{ session.biografia['Descripcion']}}</p></div>
              
              </div>
              <!-- About Section Button-->
              <div class="text-center mt-4">
                  <a class="btn btn-xl btn-outline-light" href="{{session.biografia['url_cv']}}">
                      <i class="fas fa-download me-2"></i>
                      Descargar CV!
                  </a>
              </div>
          </div>
      </section>
{% endblock %}

semana02/dia5/app/templates/portafolio/contacto.html
{% extends 'portafolio/layout.html' %}
{% block content %}
        <!-- Contact Section-->
        <section class="page-section" id="contact">
          <div class="container">
              <!-- Contact Section Heading-->
              <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Contact Me</h2>
              <!-- Icon Divider-->
              <div class="divider-custom">
                  <div class="divider-custom-line"></div>
                  <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                  <div class="divider-custom-line"></div>
              </div>
              <!-- Contact Section Form-->
              <div class="row justify-content-center">
                  <div class="col-lg-8 col-xl-7">
                      <!-- * * * * * * * * * * * * * * *-->
                      <!-- * * SB Forms Contact Form * *-->
                      <!-- * * * * * * * * * * * * * * *-->
                      <!-- This form is pre-integrated with SB Forms.-->
                      <!-- To make this form functional, sign up at-->
                      <!-- https://startbootstrap.com/solution/contact-forms-->
                      <!-- to get an API token!-->
                      <form id="contactForm" data-sb-form-api-token="API_TOKEN">
                          <!-- Name input-->
                          <div class="form-floating mb-3">
                              <input class="form-control" id="name" type="text" placeholder="Enter your name..." data-sb-validations="required" />
                              <label for="name">Full name</label>
                              <div class="invalid-feedback" data-sb-feedback="name:required">A name is required.</div>
                          </div>
                          <!-- Email address input-->
                          <div class="form-floating mb-3">
                              <input class="form-control" id="email" type="email" placeholder="name@example.com" data-sb-validations="required,email" />
                              <label for="email">Email address</label>
                              <div class="invalid-feedback" data-sb-feedback="email:required">An email is required.</div>
                              <div class="invalid-feedback" data-sb-feedback="email:email">Email is not valid.</div>
                          </div>
                          <!-- Phone number input-->
                          <div class="form-floating mb-3">
                              <input class="form-control" id="phone" type="tel" placeholder="(123) 456-7890" data-sb-validations="required" />
                              <label for="phone">Phone number</label>
                              <div class="invalid-feedback" data-sb-feedback="phone:required">A phone number is required.</div>
                          </div>
                          <!-- Message input-->
                          <div class="form-floating mb-3">
                              <textarea class="form-control" id="message" type="text" placeholder="Enter your message here..." style="height: 10rem" data-sb-validations="required"></textarea>
                              <label for="message">Message</label>
                              <div class="invalid-feedback" data-sb-feedback="message:required">A message is required.</div>
                          </div>
                          <!-- Submit success message-->
                          <!---->
                          <!-- This is what your users will see when the form-->
                          <!-- has successfully submitted-->
                          <div class="d-none" id="submitSuccessMessage">
                              <div class="text-center mb-3">
                                  <div class="fw-bolder">Form submission successful!</div>
                                  To activate this form, sign up at
                                  <br />
                                  <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                              </div>
                          </div>
                          <!-- Submit error message-->
                          <!---->
                          <!-- This is what your users will see when there is-->
                          <!-- an error submitting the form-->
                          <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Error sending message!</div></div>
                          <!-- Submit Button-->
                          <button class="btn btn-primary btn-xl disabled" id="submitButton" type="submit">Send</button>
                      </form>
                  </div>
              </div>
          </div>
      </section>
{% endblock %}

semana02/dia5/app/templates/portafolio/footer.html
   <!-- Footer-->
   <footer class="footer text-center">
    <div class="container">
        <div class="row">
            <!-- Footer Location-->
            <div class="col-lg-4 mb-5 mb-lg-0">
                <h4 class="text-uppercase mb-4">Direccion</h4>
                <p class="lead mb-0">
                    {{session.biografia['Ubicacion']}}
                    <br />
                    Clark, MO 65243
                </p>
            </div>
            <!-- Footer Social Icons-->
            <div class="col-lg-4 mb-5 mb-lg-0">
                <h4 class="text-uppercase mb-4">Enalces</h4>
                {% for e in session.enlaces %}

                    <a class="btn btn-outline-light btn-social mx-1" href="{{e['url']}}"><i class="{{e['estilos']}}"></i></a>
                    
                {% endfor %}
            </div>
            <!-- Footer About Text-->
            <div class="col-lg-4">
                <h4 class="text-uppercase mb-4">Acerca de</h4>
                <p class="lead mb-0">
                    {{session.biografia['resumen']}}
                </p>
            </div>
        </div>
    </div>
</footer>

semana02/dia5/app/templates/portafolio/home.html
{% extends 'portafolio/layout.html' %}
{% block content %}
    <header class="masthead bg-primary text-white text-center">
      <div class="container d-flex align-items-center flex-column">
          <!-- Masthead Avatar Image-->
          <img class="masthead-avatar mb-5" src="{{session.biografia['foto']}}" alt="..." />
          <!-- Masthead Heading-->
          <h1 class="masthead-heading text-uppercase mb-0">{{session.biografia['nombre']}}</h1>
          <!-- Icon Divider-->
          <div class="divider-custom divider-light">
              <div class="divider-custom-line"></div>
              <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
              <div class="divider-custom-line"></div>
          </div>
          <!-- Masthead Subheading-->
          <p class="masthead-subheading font-weight-light mb-0">{{session.biografia['resumen']}}</p>
      </div>
    </header>
{% endblock %}

semana02/dia5/app/templates/portafolio/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

    <title>MI SITIO WEB!</title>
  </head>
  <body>
    <h1>
      {% if nombre != 'no hay nombre' %}
      BIENVENIDO {{nombre}} !
      {% endif %}
    </h1>
    {%block content%}
    {%endblock%}
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>

  </body>
</html>

semana02/dia5/app/templates/portafolio/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Freelancer - Start Bootstrap Theme</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{{url_for('static',  filename='assets/favicon.ico')}}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{{ url_for('static', filename='css/styles.css')}}" rel="stylesheet" />
    </head>
    <body id="page-top">
        {% include 'portafolio/navbar.html' %}
       
        {% block content %}
        {% endblock %}
        {% include 'portafolio/footer.html' %}
        {% include 'portafolio/modals.html' %}
        
        <!-- Copyright Section-->
        <div class="copyright py-4 text-center text-white">
            <div class="container"><small>Copyright &copy; Your Website 2022</small></div>
        </div>
   
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{{url_for('static',  filename='js/scripts.js')}}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

semana02/dia5/app/templates/portafolio/modals.html
     <!-- Portfolio Modals-->
        <!-- Portfolio Modal 1-->
        {% for p in proyectos %}
        <div class="portfolio-modal modal fade" id="portfolioModal1_{{p['codigo']}}" tabindex="-1" aria-labelledby="portfolioModal1" aria-hidden="true">
          <div class="modal-dialog modal-xl">
              <div class="modal-content">
                  <div class="modal-header border-0"><button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button></div>
                  <div class="modal-body text-center pb-5">
                      <div class="container">
                          <div class="row justify-content-center">
                              <div class="col-lg-8">
                                  <!-- Portfolio Modal - Title-->
                                  <h2 class="portfolio-modal-title text-secondary text-uppercase mb-0">{{p['nombre']}}</h2>
                                  <!-- Icon Divider-->
                                  <div class="divider-custom">
                                      <div class="divider-custom-line"></div>
                                      <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                                      <div class="divider-custom-line"></div>
                                  </div>
                                  <!-- Portfolio Modal - Image-->
                                  <img class="img-fluid rounded mb-5" src="{{p['imagen']}}" alt="..." />
                                  <!-- Portfolio Modal - Text-->
                                  <p class="mb-4">{{p['descripcion']}}</p>
                                  <button class="btn btn-primary" data-bs-dismiss="modal">
                                      <i class="fas fa-xmark fa-fw"></i>
                                      Close Window
                                  </button>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    {% endfor %}
      <!-- Portfolio Modal 2-->
     

semana02/dia5/app/templates/portafolio/navbar.html
 <!-- Navigation-->
 <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
  <div class="container">
      <a class="navbar-brand" href="{{url_for('portafolio.home')}}">Mi Portafolio</a>
      <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{{url_for('portafolio.proyectos')}}">Portfolio</a></li>
            <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{{url_for('portafolio.about')}}">About</a></li>
            <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{{url_for('portafolio.contacto')}}">Contact</a></li>
            
          </ul>
      </div>
  </div>
</nav>

semana02/dia5/app/templates/portafolio/peliculas.html
{%extends 'index.html'%}
{%block content%}
  <ul>
    {% for peli in peliculas %}
    <li>{{peli}}</li>
    {% endfor %}
  </ul>
{%endblock%}

  

semana02/dia5/app/templates/portafolio/portafolio.html
{% extends 'portafolio/layout.html' %}
{% block content %}
      <!-- Portfolio Section-->
      <section class="page-section portfolio" id="portfolio">
        <div class="container">
            <!-- Portfolio Section Heading-->
            <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Portafolio</h2>
            <!-- Icon Divider-->
            <div class="divider-custom">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                <div class="divider-custom-line"></div>
            </div>
            <!-- Portfolio Grid Items-->
            <div class="row justify-content-center">
                <!-- Portfolio Item 1-->
            {% for p in proyectos %}
                <div class="col-md-6 col-lg-4 mb-5">
                    <div class="portfolio-item mx-auto" data-bs-toggle="modal" data-bs-target="#portfolioModal1_{{p['codigo']}}">
                        <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                            <div class="portfolio-item-caption-content text-center text-white"><i class="fas fa-plus fa-3x"></i></div>
                        </div>
                        <img class="img-fluid" src="{{p['imagen']}}" alt="..." />
                    </div>
                </div>
            {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}