semana04/dia1/encuesta/appfront/urls.py
from unicodedata import name
from django.urls  import path
from . import views

app_name = 'appfront'

urlpatterns = [
  path('', views.app_index, name='index'),
  path('<int:pregunta_id>', views.detalle, name= 'detalle'),
  path('enviar', views.enviar, name = 'enviar')
]

semana04/dia1/encuesta/encuesta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse

def index(request):
    return HttpResponse("<center><h1>Hola mundo en django</h1></center>")
    
urlpatterns = [
    path('', index),
    path('encuesta/',include('appfront.urls')),
    path('admin/', admin.site.urls),
]

semana04/dia1/encuesta/appfront/models.py
from django.db import models

# Create your models here.

semana04/dia1/encuesta/appfront/views.py
import imp
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def  app_index(request):
  #return HttpResponse('<h1>INDEX DE MI APP</h1>')
  titulo = 'ENCUESTA A ALUMNOS'
  context = {
    'titulo':titulo
  }
  
  return render(request, 'index.html', context)

def detalle(request, pregunta_id):
  return HttpResponse('pregunta nro %s.'%pregunta_id)

def enviar(request):
  contex = {
    'titulo':'RESULTADO DE LA ENCUESTA',
    'nombre': request.POST['nombre'],
    'rol':request.POST['rol'],
    'idiomas': request.POST.getlist('idiomas')
  }
  
  return render(request, 'respuesta.html', contex)

semana04/dia1/encuesta/appfront/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  
  <center><h1>{{titulo}}</h1></center>
  <form action="{% url 'appfront:enviar' %}" method="post">
    {% csrf_token %}
    Nombre: <input type="text" name="nombre">
    </br>
    Cual es tu rol favorito:
    <select name = "rol">
      <option>Front End</option>
      <option>Backend</option>
    </select>
    </br>
    Que idiomas hablas:
    <input type="checkbox" name="idiomas" value="español" checked = 'checked'>Español</input>
    <input type="checkbox" name="idiomas" value="ingles" >Ingles</input>
    <input type="checkbox" name="idiomas" value="frances" >Frances</input>
    <input type="checkbox" name="idiomas" value="aleman" >Aleman</input>
    </br>
    <input type="submit" name="enviar" value="Completar Encuesta">
  </form>
  
</body>
</html>

semana04/dia1/encuesta/appfront/templates/respuesta.html
<h2>{{ titulo }}</h2>
<ol>
    <li>Nombre : {{ nombre }}</li>
    <li>Rol favorito : {{ rol }}</li>
    <li>Idiomas:
        <ul>
            {% for i in idiomas %}
                <li>{{ i }}</li>
            {% endfor %}
        </ul>
    </li>
</ol>