semana04/dia4/shop/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('web.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

semana04/dia4/web/urls.py
from django.urls import path

from . import views

app_name = 'web'

urlpatterns = [
  path('', views.index, name='index'),
  path('producto/<int:producto_id>', views.producto, name='producto'),
  path('productosPorCategoria/<int:categoria_id>', views.productosPorCategoria, name='productosPorCategoria'),
  path('carrito', views.carrito, name='carrito'),
  path('agregarCarrito/<int:producto_id>', views.agregarCarrito, name='agregarCarrito'),
  path('eliminarProductoCarrito/<int:producto_id>',views.eliminarProductoCarrito,name='eliminarProductoCarrito'),
  path('limpiarCarrito',views.limpiarCarrito,name='limpiarCarrito'),
  path('login', views.loginUsuario, name='loginUsuario'),
  path('crearUsuario', views.crearUsuario, name='crearUsuario'),
  path('cuenta', views.cuentaUsuario, name='cuentaUsuario'),
  path('actualizarCliente',views.actualizarCliente,name='actualizarCliente'),
  path('registrarPedido',views.registrarPedido,name='registrarPedido')
]

semana04/dia4/web/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Categorias(models.Model):
  nombre = models.CharField(max_length=200)
  pub_date = models.DateTimeField(auto_now=True)
  
  def __str__(self):
    return self.nombre
  
class Productos(models.Model):
  categoria = models.ForeignKey(Categorias, on_delete=models.RESTRICT)
  nombre = models.CharField(max_length=200)
  precio = models.DecimalField(max_digits=9, decimal_places=2)
  stock = models.IntegerField(default=0)
  pub_date = models.DateTimeField(auto_now=True)
  imagen = models.ImageField(upload_to='productos/', blank=True)
  
  def __str__(self):
    return self.nombre
  
class CLiente(models.Model):
  usuario = models.OneToOneField(User, on_delete=models.RESTRICT)
  direccion = models.CharField(max_length=200)
  telefono = models.CharField(max_length=20)
  
  def __str__(self):
    return self.telefono
  
class Pedido(models.Model):
  cliente = models.ForeignKey(CLiente, on_delete=models.RESTRICT)
  fecha_reg = models.DateField(auto_now=True)
  
  def __str__(self):
    return str(self.fecha_reg)
  
class pedidoDetalle(models.Model):
  pedido = models.ForeignKey(Pedido, on_delete=models.RESTRICT)
  producto = models.ForeignKey(Productos, on_delete=models.RESTRICT)
  cantidad = models.IntegerField(default=0)
  
  def __str__(self):
    return  self.producto.nombre
  

semana04/dia4/web/views.py
from multiprocessing.connection import Client
from django.shortcuts import render, redirect
from .models import Categorias, Productos
from .carrito import Cart

# Create your views here.
def index(request):
    request.session['titulo'] = "MODA DJANGO"
    listaProductos = Productos.objects.all()
    listaCategorias = Categorias.objects.all()
    context = {
        'productos': listaProductos,
        'categorias': listaCategorias
    }
    return render(request, 'index.html', context)

def producto(request, producto_id):
    objProducto = Productos.objects.get(pk=producto_id)
    context = {
        'producto': objProducto
    }
    return render(request, 'producto.html', context)

def productosPorCategoria(request, categoria_id):
    objCategoria = Categorias.objects.get(pk = categoria_id)
    listProductos = objCategoria.productos_set.all()
    listaCategorias = Categorias.objects.all()
    context = {
        'productos': listProductos,
        'categorias': listaCategorias
    }
    return render(request, 'index.html', context)
######### CARRITO DE COMPRAS ##########################

from web.carrito import Cart

def carrito(request):
    return render(request,'carrito.html')

def agregarCarrito(request,producto_id):
    objProducto = Productos.objects.get(id=producto_id)
    carritoProducto = Cart(request)
    carritoProducto.add(objProducto,1)
    print(request.session.get("cart"))
    
    return render(request,'carrito.html')

def eliminarProductoCarrito(request,producto_id):
    """
    funcion que elimina un producto del carrito de compras
    """
    objProducto = Productos.objects.get(id=producto_id)
    carritoProducto = Cart(request)
    carritoProducto.delete(objProducto)
    return render(request,'carrito.html')

def limpiarCarrito(request):
    carritoProducto = Cart(request)
    carritoProducto.clear()
    return render(request,'carrito.html')

##################### LOGIN DE USUARIO #############################
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate

def loginUsuario(request):
    context = {}
    if request.method == 'POST':
        #login de usuarios
        dataUsuario = request.POST['usuario']
        dataPassword = request.POST['password']
        usuarioAuth = authenticate(username=dataUsuario, password=dataPassword)
        
        if usuarioAuth is not None:
            login(request, usuarioAuth)
            return redirect('/cuenta')
        else:
            context = {'error': 'Usuario o contraseña incorrectos'}
        
    return render(request,'login.html', context)

def crearUsuario(request):
    
    if  request.method == 'POST':
        
        dataUsuario = request.POST['nuevoUsuario']
        dataPassword = request.POST['nuevoPassword']
        
        nuevoUsuario = User.objects.create_user(username=dataUsuario, password=dataPassword)
        login(request, nuevoUsuario)
        
        return redirect('/cuenta')

from .form import ClienteForm
from .models import CLiente    

def cuentaUsuario(request):
    #buscar si existe el cliente usuario
    try:
        clienteEditar = CLiente.objects.get(usuario = request.user)
        dataCliente = {
            'nombre':request.user.first_name,
            'apellidos': request.user.last_name,
            'email': request.user.email,
            'direccion':clienteEditar.direccion,
            'telefono':clienteEditar.telefono,
            'usuario':request.user.username,
        }
    except:
        dataCliente = {
            'nombre':request.user.first_name,
            'apellidos': request.user.last_name,
            'email': request.user.email,
            'usuario':request.user.username,
        }
    
    frmCliente =  ClienteForm(dataCliente)
    
    context = {
        'frmCliente' : frmCliente
    }
    
    return render(request, 'cuenta.html', context)

def actualizarCliente(request):
    mensaje = ""
    if request.method == 'POST':
        frmCliente = ClienteForm(request.POST)
        if frmCliente.is_valid():
            dataCliente = frmCliente.cleaned_data

            #actualización de usuario
            actUsuario = User.objects.get(pk=request.user.id)
            actUsuario.first_name = dataCliente["nombre"]
            actUsuario.last_name = dataCliente["apellidos"]
            actUsuario.email = dataCliente["email"]
            actUsuario.save()

            try:
                actCliente = CLiente.objects.get(usuario = request.user)
                actCliente.direccion = dataCliente["direccion"]
                actCliente.telefono = dataCliente["telefono"]
                actCliente.save()
            except:
                nuevoCliente = CLiente()
                nuevoCliente.usuario = actUsuario
                nuevoCliente.direccion = dataCliente["direccion"]
                nuevoCliente.telefono = dataCliente["telefono"]
                nuevoCliente.save()
            
            mensaje = "DATOS ACTUALIZADOS CORRECTAMENTE"
        else:
            mensaje = "ERROR AL ACTUALIZAR LOS DATOS"

    context = {
        'mensaje':mensaje,
        'frmCliente':frmCliente
    }

    return render(request,'cuenta.html',context)


########### PEDIDOS ########################
from .models import Pedido,pedidoDetalle

def registrarPedido(request):
    if request.user.id is not None:
        #registra cabecera del pedido
        clientePedido = CLiente.objects.get(usuario=request.user)
        nuevoPedido = Pedido()
        nuevoPedido.cliente = clientePedido
        nuevoPedido.save()

        #registra detalle del pedido
        carritoPedido = request.session.get("cart")
        for key,value in carritoPedido.items():

            productoPedido = Productos.objects.get(pk=value["producto_id"])

            nuevoPedidoDetalle = pedidoDetalle()
            nuevoPedidoDetalle.pedido = nuevoPedido
            nuevoPedidoDetalle.producto = productoPedido
            nuevoPedidoDetalle.cantidad = int(value["cantidad"])
            nuevoPedidoDetalle.save()

        carrito = Cart(request)
        carrito.clear()

        return render(request,'gracias.html')

    else:
        return redirect('/login')

semana04/dia4/web/templates/carrito.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="maincont-ttl">Cart</h1>
    <ul class="b-crumbs">
        <li><a href="index.html">Home</a></li>
        <li>Cart</li>
    </ul>                                                    <div class="page-styling">


    <div class="woocommerce prod-litems section-list">
        {% for key,value in request.session.cart.items %}
        <article class="prod-li sectls">
            <div class="prod-li-inner">
                <a href="product.html" class="prod-li-img">
                    <img src="{{ value.imagen }}" alt="">
                </a>
                <div class="prod-li-cont">
                    <div class="prod-li-ttl-wrap">
                        <p>
                            <a href="#">{{ value.categoria }}</a>
                        </p>
                        <h3><a href="product.html">{{ value.nombre }}</a></h3>
                    </div><!--
    No Space
    --><div class="prod-li-prices">
                    <div class="prod-li-price-wrap">
                        <p>Price</p>
                        <p class="prod-li-price">${{ value.precio }}</p>
                    </div>
                    <div class="prod-li-qnt-wrap">
                        <p class="qnt-wrap prod-li-qnt">
                            <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                            <input type="text" value="{{ value.cantidad }}">
                            <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                        </p>
                    </div>
                    <div class="prod-li-total-wrap">
                        <p>Total</p>
                        <p class="prod-li-total">${{ value.total }}</p>
                    </div>
                </div><!--
No Space
--></div>
                <div class="prod-li-info">
                    <div class="prod-li-rating-wrap">
                        <p data-rating="5" class="prod-li-rating">
                            <i class="rating-ico" title="1"></i><i class="rating-ico" title="2"></i><i class="rating-ico" title="3"></i><i class="rating-ico" title="4"></i><i class="rating-ico" title="5"></i>
                        </p>
                        <p class="prod-li-rating-count">12</p>
                    </div>
                    <p class="prod-li-add">
                        <a href="{% url 'web:eliminarProductoCarrito' value.producto_id %}" class="button hover-label prod-addbtn"><i class="icon ion-close-round"></i><span>Eliminar</span></a>
                    </p>
                    <p class="prod-li-compare">
                        <a href="compare.html" class="hover-label prod-li-compare-btn"><span>Compare</span><i class="icon ion-arrow-swap"></i></a>
                    </p>
                    <p class="prod-quickview">
                        <a href="#" class="hover-label quick-view"><i class="icon ion-plus"></i><span>Quick View</span></a>
                    </p>
                    <div class="prod-li-favorites">
                        <a href="wishlist.html" class="hover-label add_to_wishlist"><i class="icon ion-heart"></i><span>Add to Wishlist</span></a>
                    </div>
                    <p class="prod-li-information">
                        <a href="#" class="hover-label"><i class="icon ion-more"></i><span>Show Information</span></a>
                    </p>
                </div>
            </div>
            <div class="page-styling prod-li-informations">

                <dl class="prod-li-props">
                    <dt>Brand:</dt>
                    <dd><a href="#">AIR</a></dd>
                    <dt>Weight:</dt>
                    <dd>1 kg</dd>
                    <dt>Dimensions:</dt>
                    <dd>4 x 50 cm</dd>
                    <dt>Сolor:</dt>
                    <dd><a href="#" rel="tag">Black</a>, <a href="#" rel="tag">Green</a></dd>
                    <dt>Manufacturer:</dt>
                    <dd><a href="#">France</a></dd>
                    <dt>Material:</dt>
                    <dd><a href="#" rel="tag">Metall</a>, <a href="#" rel="tag">Plastic</a>, <a href="#" rel="tag">Rubber</a></dd>
                </dl>
            </div>
        </article>
        {% endfor %}
    </div>


    <div class="cart-actions">
        <div class="coupon">
            <input type="text" placeholder="Coupon code">
            <input type="submit" class="button" value="Apply">
        </div>
        <div class="cart-collaterals">
            <a href="{% url 'web:limpiarCarrito' %}" class="checkout-button button">Limpiar Carrito</a>
            <a href="#" class="checkout-button button">Proceed to checkout</a>
            <div class="order-total">
                <p class="cart-totals-ttl">Total</p>
                <p class="cart-totals-val">${{ request.session.cartMontoTotal }}</p>
            </div>
        </div>
    </div>


</div>

{% endblock %}

semana04/dia4/web/templates/cuenta.html
{% extends "layout.html" %} 
{% block content %}
<h1 class="maincont-ttl">Mi cuenta - {{ user.get_username  }}</h1>
    <ul class="b-crumbs">
        <li>Mi cuenta</li>
    </ul>
    <h2>{{mensaje}}</h2>
    <article class="page-cont">
        <form method="post" action="{% url 'web:actualizarCliente' %}" class="register">
            {% csrf_token %}
            {{ frmCliente.as_p }}
            <p class="auth-sumit">
                <input type="submit" value="Actualizar">
            </p>
        </form>
    </article>
{% endblock %}

semana04/dia4/web/templates/index.html
{% extends "layout.html" %}
{% block content %}
<div class="section-top">

    <h1 class="maincont-ttl">{{ request.session.titulo }}</h1>
    <ul class="b-crumbs">
        <li><a href="index.html">Home</a></li>
        <li>Catalog - Gallery</li>
    </ul>
    <div class="section-top-sort">
        <div class="section-view">
            <p>View</p>
            <div class="dropdown-wrap">
                <p class="dropdown-title section-view-ttl">Gallery</p>
                <ul class="dropdown-list">
                    <li>
                        <a href="catalog-list.html">List</a>
                    </li>
                    <li class="active">
                        <a href="catalog-gallery.html">Gallery</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="section-sort">
            <p>Sort</p>
            <div class="dropdown-wrap">
                <p class="dropdown-title section-sort-ttl">Newness</p>
                <ul class="dropdown-list">
                    <li>
                        <a href="#">Popularity</a>
                    </li>
                    <li>
                        <a href="#">Average rating</a>
                    </li>
                    <li class="active">
                        <a href="#">Newness</a>
                    </li>
                    <li>
                        <a href="#">Price: low to high</a>
                    </li>
                    <li>
                        <a href="#">Price: high to low</a>
                    </li>
                </ul>
            </div>
        </div>
        <form method="post" class="products-per-page">
            <p>Per Page</p>
            <select>
                <option value="12" selected="selected">12</option>
                <option value="24">24</option>
                <option value="48">48</option>
                <option value="-1">All</option>
            </select>
        </form>
    </div>
</div>

<!-- To make Sidebar "Not Sticky" just remove  id="section-list-withsb" -->
<div class="section-wrap-withsb">
    <aside class="blog-sb-widgets section-sb" id="section-sb">
        <div class="theiaStickySidebar">
            <p class="section-filter-toggle filter_hidden">
                <a href="#" id="section-filter-toggle-btn">Show Filter</a>
            </p>
            <div class="section-filter">
                <div class="section-filter">
                    <div class="blog-sb-widget multishopcategories_widget">
                        <h3 class="widgettitle">Categorias</h3>
                        <div class="section-sb-current">
                            <ul class="section-sb-list">
                                {% for categoria in categorias %}
                                <li>
                                    <a href="{% url 'web:productosPorCategoria' categoria.id %}"><span class="section-sb-label">{{categoria.nombre}} <span class="count">{{categoria.productos_set.all.count}}</span></span></a>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>


                    <div class="blog-sb-widget multishopfeaturedproducts_widget">
                        <h3 class="widgettitle">Featured</h3>
                        <div class="products-featured-wrap">
                            <div class="products-featured">
                                <p class="products-featured-categ">
                                    <a href="#">Tools</a>
                                </p>
                                <h5 class="products-featured-ttl"><a href="product.html">Rechargeable Battery</a></h5>
                                <p class="products-featured-price">$201.00</p>
                            </div>
                            <div class="products-featured">
                                <p class="products-featured-categ">
                                    <a href="#">Pipes</a>
                                </p>
                                <h5 class="products-featured-ttl"><a href="product.html">Wholesale Brass</a></h5>
                                <p class="products-featured-price">$15.00</p>
                            </div>
                            <div class="products-featured">
                                <p class="products-featured-categ">
                                    <a href="#">Pipes</a>
                                </p>
                                <h5 class="products-featured-ttl"><a href="product.html">Fittings Pipe</a></h5>
                                <p class="products-featured-price">$77.00</p>
                            </div>
                            <div class="products-featured">
                                <p class="products-featured-categ">
                                    <a href="#">Pipes</a>
                                </p>
                                <h5 class="products-featured-ttl"><a href="product.html">Fittings Pipe</a></h5>
                                <p class="products-featured-price">$105.00</p>
                            </div>
                            <div class="products-featured">
                                <p class="products-featured-categ">
                                    <a href="#">Fasteners</a>
                                </p>
                                <h5 class="products-featured-ttl"><a href="product.html">Flat Bolt</a></h5>
                                <p class="products-featured-price">$45.00</p>
                            </div>
                        </div>
                    </div>
                    <div class="blog-sb-widget multishopbrands_widget">
                        <h3 class="widgettitle">Brands</h3>
                        <ul class="brands-list-sb">
                            <li>
                                <a href="#">HOOK <span class="count">5</span></a>
                            </li>
                            <li>
                                <a href="#">Fuel Tank <span class="count">7</span></a>
                            </li>
                            <li>
                                <a href="#">BMP <span class="count">17</span></a>
                            </li>
                            <li>
                                <a href="#">BISON <span class="count">9</span></a>
                            </li>
                            <li>
                                <a href="#">AIR <span class="count">6</span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </aside>        <div class="section-list-withsb" id="section-list-withsb">
    <div class="theiaStickySidebar">

        <!--
        Gallery Item Columns:
        With Sidebar:
        prod-items-4 : cf-sm-6 cf-md-6 cf-lg-3 col-xs-6 col-sm-6 col-md-6 col-lg-3
        prod-items-3 : cf-sm-6 cf-md-6 cf-lg-4 col-xs-6 col-sm-6 col-md-6 col-lg-4
        Without Sidebar:
        prod-items-4 : cf-sm-6 cf-md-4 cf-lg-3 col-xs-6 col-sm-6 col-md-4 col-lg-3
        prod-items-3 : cf-sm-6 cf-md-4 cf-lg-4 col-xs-6 col-sm-6 col-md-4 col-lg-4
        For Both:
        prod-items-2 : cf-sm-6 cf-md-6 cf-lg-6 col-xs-6 col-sm-6 col-md-6 col-lg-6
        prod-items-1 : col-lg-12
        -->
        <div class="row prod-items prod-items-2">
            {% for producto in productos %}
            <article class="cf-sm-6 cf-md-6 cf-lg-6 col-xs-6 col-sm-6 col-md-6 col-lg-6 sectgl-item">
                <div class="sectgl prod-i">
                    <div class="prod-i-top">
                        <a class="prod-i-img" href="{% url 'web:producto' producto.id %}">
                            <img src="{{ producto.imagen.url }}" alt="">
                        </a>
                        <div class="prod-i-actions">
                            <div class="prod-i-actions-in">
                                <div class="prod-li-favorites">
                                    <a href="wishlist.html" class="hover-label add_to_wishlist"><i class="icon ion-heart"></i><span>Add to Wishlist</span></a>
                                </div>
                                <p class="prod-quickview">
                                    <a href="#" class="hover-label quick-view"><i class="icon ion-plus"></i><span>Quick View</span></a>
                                </p>
                                <p class="prod-i-cart">
                                    <a href="#" class="hover-label prod-addbtn"><i class="icon ion-android-cart"></i><span>Add to Cart</span></a>
                                </p>
                                <p class="prod-li-compare">
                                    <a href="compare.html" class="hover-label prod-li-compare-btn"><span>Compare</span><i class="icon ion-arrow-swap"></i></a>
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="prod-i-bot">
                        <div class="prod-i-info">
                            <p class="prod-i-price">${{ producto.precio }}</p>
                            <p class="prod-i-categ"><a href="catalog-gallery.html">{{ producto.categoria.nombre }}</a></p>
                        </div>
                        <h3 class="prod-i-ttl"><a href="{% url 'web:producto' producto.id %}">{{ producto.nombre }}</a></h3>
                    </div>
                </div>
            </article>            
            {% endfor %}
        </div>
        <ul class="page-numbers">
            <li><span class="page-numbers current">1</span></li>
            <li><a class="page-numbers" href="#">2</a></li>
            <li><a class="page-numbers" href="#">3</a></li>
            <li><a class="page-numbers" href="#">4</a></li>
            <li><a class="next page-numbers" href="#"><i class="fa fa-angle-right"></i></a></li>
        </ul>
    </div><!-- .theiaStickySidebar -->
</div><!-- .section-list-withsb -->
</div><!-- .section-wrap-withsb -->
{% endblock %}

semana04/dia4/web/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="maincont-ttl">Registration / Login</h1>
    <ul class="b-crumbs">
        <li><a href="index.html">Home</a></li>
        <li>Registration & Login</li>
    </ul>                                                
    <article class="page-cont">
    <div class="page-styling">


        <div class="auth-wrap">
            <div class="auth-col">
                <h2>Login</h2>
                <form method="post" class="login" action="{% url 'web:loginUsuario'  %}">
                    {% csrf_token %}
                    <p>
                        <label for="username">E-mail <span class="required">*</span></label>
                        <input type="text" id="username" name="usuario">
                    </p>
                    <p>
                        <label for="password">Password <span class="required">*</span></label>
                        <input type="password" id="password" name="password">
                    </p>
                    <p class="auth-submit">
                        <input type="submit" value="Login">
                        <input type="checkbox" id="rememberme" value="forever">
                        <label for="rememberme">Remember me</label>
                    </p>
                    <p>
                        <label for="alert-danger">{{ error }}</label>
                    </p>
                    <p class="auth-lost_password">
                        <a href="#">Lost your password?</a>
                    </p>
                </form>
            </div>
            <div class="auth-col">
                <h2>Nuevo Usuario</h2>
                <form method="post" class="register" action="{% url 'web:crearUsuario' %}">
                    {% csrf_token %}
                    <p>
                        <label for="reg_email">Email <span class="required">*</span></label>
                        <input type="email" id="reg_email" name="nuevoUsuario">
                    </p>
                    <p>
                        <label for="reg_password">Password <span class="required">*</span></label>
                        <input type="password" id="reg_password" name="nuevoPassword">
                    </p>
                    <p class="auth-submit">
                        <input type="submit" value="Register">
                    </p>
                </form>
            </div>
        </div>


    </div>
    </article>
{% endblock %}