semana04/dia2/recetas/app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
  path('', views.index, name='index'),
  path('RegistrarReceta', views.registrarReceta, name='registrarReceta')
]

semana04/dia2/recetas/recetas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

semana04/dia2/recetas/app/models.py
from statistics import mode
from django.db import models

# Create your models here.
class Autor(models.Model):
  nombre = models.CharField(max_length=200)
  email = models.EmailField(unique=True)
  
  def __str__(self):
    return self.nombre
  
  
  
class Receta(models.Model):
  titulo = models.CharField(max_length=100)
  ingredientes = models.TextField(help_text='redacta los ingredientes')
  preparacion = models.TextField()
  tiempo_registro = models.DateTimeField(auto_now=True)
  autor = models.ForeignKey(Autor, on_delete=models.RESTRICT)
  
  def __str__(self):
    return self.titulo
  
class Comentario(models.Model):
  receta = models.ForeignKey(Receta, on_delete=models.CASCADE)
  texto = models.TextField(help_text='comentario')
  
  def __str__(self):
    return self.texto

semana04/dia2/recetas/app/forms.py
from django import forms

class RecetaForm(forms.Form):
  titulo = forms.CharField(label='Título', max_length=100, required=True)
  ingredientes = forms.CharField(label='Ingredientes', widget=forms.Textarea)
  preparacion = forms.CharField(label='Preparación', widget=forms.Textarea)
  autor = forms.CharField(label='Autor', max_length=100, required=True)
  

semana04/dia2/recetas/app/views.py
from django.shortcuts import render,redirect
from . models import Receta
from .forms import RecetaForm

# Create your views here.
def index(request):
  listaRecetas = Receta.objects.all()
  
  #formulario de nueva receta
  frmReceta = RecetaForm()
  context = {
    'frmReceta': frmReceta,
    'recetas': listaRecetas
  }
  
  return render(request, 'index.html', context)

def registrarReceta(request):
  frmReceta = RecetaForm(request.POST)
  if frmReceta.is_valid():
    dataReceta = frmReceta.cleaned_data
    print(dataReceta)
    #insertamos la receta en la tabla
    nuevaReceta= Receta()
    nuevaReceta.titulo = dataReceta['titulo']
    nuevaReceta.ingredientes = dataReceta['ingredientes']
    nuevaReceta.preparacion = dataReceta['preparacion']
    nuevaReceta.autor = dataReceta['autor']
    nuevaReceta.save()
    return redirect('/')

semana04/dia2/recetas/app/templates/index.html
{% load crispy_forms_tags %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <title>recetas</title>
  </head>
  <body>
    <div class="container-fluid">
      
      <div class="container">
        <h1>Recetas</h1>
        <div class="row">
          {% for receta in recetas %}
          <div class="col-sm">
            <div class="card" style="width: 18rem;">
              <div class="card-body">
                <h5 class="card-title">{{ receta.titulo }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">ingredientes:</h6>
                <p class="card-text">{{ receta.ingredientes }}</p>
                <h6 class="card-subtitle mb-2 text-muted">preparación:</h6>
                <p class="card-text">{{ receta.preparacion }}</p>
                <a href="#" class="card-link">{{ receta.autor }}</a>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
        <br/>

        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
          Nueva receta
        </button>

        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Nueva Receta</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <form method="post" action="{% url 'app:registrarReceta' %}">
                  {% csrf_token %}
                  {{frmReceta | crispy}}
                  <p>
                    <button type="submit" class="btn btn-primary">Registrar</button>
                  </p>
                </form>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>

        
    </div>
  
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
      crossorigin="anonymous"></script>
  

  </body>
</html>